services:
  app:
    build:
      context: .
    container_name: pywan
    ports:
      - "8001:8001"  # Mapeie para a porta correta da sua aplicação
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Para saída de log ao vivo
    tty: true
    networks:
      - server-network


networks:
  server-network:
    driver: default
    name: network-flugel
    external: true
